import { JobFinderRepositoryStateSchema, type JobFinderRepositoryState } from "@unemployed/contracts";
import { createEmptyJobFinderRepositoryState } from "./job-finder-initial-state";

export function createResumeWorkspaceDemoState(): JobFinderRepositoryState {
  const emptyState = createEmptyJobFinderRepositoryState();

  return JobFinderRepositoryStateSchema.parse({
    ...emptyState,
    profile: {
      ...emptyState.profile,
      id: "candidate_1",
      firstName: "Alex",
      lastName: "Vanguard",
      fullName: "Alex Vanguard",
      headline: "Senior systems designer",
      summary: "Builds resilient workflows for design systems, workflow automation, and operations platforms.",
      currentLocation: "London, UK",
      yearsExperience: 10,
      email: "alex@example.com",
      phone: "+44 7700 900123",
      portfolioUrl: "https://alex.example.com",
      linkedinUrl: "https://www.linkedin.com/in/alex-vanguard",
      baseResume: {
        ...emptyState.profile.baseResume,
        id: "resume_1",
        fileName: "alex-vanguard.pdf",
        uploadedAt: "2026-03-20T10:00:00.000Z",
        storagePath: "/tmp/alex-vanguard.pdf",
        textContent:
          "Alex Vanguard\nSenior systems designer\nLondon, UK\nalex@example.com\n+44 7700 900123\nhttps://alex.example.com\nhttps://www.linkedin.com/in/alex-vanguard\n\n10 years of experience building resilient workflow tools with Figma, React, and design systems.",
        textUpdatedAt: "2026-03-20T10:00:00.000Z",
        extractionStatus: "ready",
        lastAnalyzedAt: "2026-03-20T10:01:00.000Z",
        analysisWarnings: [],
      },
      targetRoles: ["Principal Designer"],
      locations: ["Remote"],
      skills: ["Figma", "React", "Design Systems"],
      experiences: [
        {
          id: "experience_1",
          companyName: "Signal Systems",
          companyUrl: null,
          title: "Senior systems designer",
          employmentType: "Full-time",
          location: "London, UK",
          workMode: ["hybrid"],
          startDate: "2020-01",
          endDate: null,
          isCurrent: true,
          isDraft: false,
          summary: "Builds resilient workflow tools.",
          achievements: ["Led design-system rollout across core workflow surfaces."],
          skills: ["Figma", "Design Systems"],
          domainTags: [],
          peopleManagementScope: null,
          ownershipScope: null,
        },
      ],
      education: [
        {
          id: "education_1",
          schoolName: "Royal College of Art",
          degree: "MA",
          fieldOfStudy: "Design Products",
          location: "London, UK",
          startDate: "2012-09",
          endDate: "2014-06",
          isDraft: false,
          summary: null,
        },
      ],
      links: [
        {
          id: "link_1",
          label: "Portfolio",
          url: "https://alex.example.com",
          kind: "portfolio",
          isDraft: false,
        },
      ],
    },
    searchPreferences: {
      ...emptyState.searchPreferences,
      targetRoles: [
        "Principal Designer",
        "Senior Product Designer",
        "Principal UX Engineer",
      ],
      locations: ["Remote", "London"],
      workModes: ["remote", "hybrid"],
      seniorityLevels: ["senior"],
      minimumSalaryUsd: 170000,
      salaryCurrency: "USD",
      companyWhitelist: ["Signal Systems"],
      discovery: {
        historyLimit: 5,
        targets: [
          {
            id: "target_linkedin_default",
            label: "Primary target",
            startingUrl: "https://www.linkedin.com/jobs/search/",
            enabled: true,
            adapterKind: "auto",
            customInstructions: null,
            instructionStatus: "missing",
            validatedInstructionId: null,
            draftInstructionId: null,
            lastDebugRunId: null,
            lastVerifiedAt: null,
            staleReason: null,
          },
        ],
      },
    },
    savedJobs: [
      {
        id: "job_ready",
        source: "target_site",
        sourceJobId: "linkedin_signal_ready",
        discoveryMethod: "catalog_seed",
        canonicalUrl: "https://www.linkedin.com/jobs/view/linkedin_signal_ready",
        title: "Senior Product Designer",
        company: "Signal Systems",
        location: "Remote",
        workMode: ["remote"],
        applyPath: "easy_apply",
        easyApplyEligible: true,
        postedAt: "2026-03-20T09:00:00.000Z",
        postedAtText: null,
        discoveredAt: "2026-03-20T09:05:00.000Z",
        salaryText: "$180k - $220k",
        summary: "Own the design system.",
        description: "Own the design system and workflow platform.",
        keySkills: ["Figma", "Design Systems"],
        responsibilities: ["Own the design system roadmap."],
        minimumQualifications: ["Strong product design systems experience."],
        preferredQualifications: ["Workflow-platform product background."],
        seniority: "Senior",
        employmentType: "Full-time",
        department: "Design",
        team: "Design Systems",
        employerWebsiteUrl: "https://signalsystems.example.com",
        employerDomain: "signalsystems.example.com",
        benefits: ["Remote-first collaboration"],
        status: "ready_for_review",
        matchAssessment: {
          score: 96,
          reasons: ["Strong design-systems overlap"],
          gaps: [],
        },
        provenance: [],
      },
      {
        id: "job_generating",
        source: "target_site",
        sourceJobId: "linkedin_northwind_generating",
        discoveryMethod: "catalog_seed",
        canonicalUrl: "https://www.linkedin.com/jobs/view/linkedin_northwind_generating",
        title: "Principal UX Engineer",
        company: "Northwind Labs",
        location: "Hybrid, London",
        workMode: ["hybrid"],
        applyPath: "easy_apply",
        easyApplyEligible: true,
        postedAt: "2026-03-20T08:00:00.000Z",
        postedAtText: null,
        discoveredAt: "2026-03-20T08:05:00.000Z",
        salaryText: "$175k - $205k",
        summary: "Lead cross-functional UI platform work.",
        description:
          "Lead cross-functional UI platform work with portfolio review required.",
        keySkills: ["React"],
        responsibilities: ["Lead UI platform architecture."],
        minimumQualifications: ["Deep React experience."],
        preferredQualifications: ["Accessibility leadership experience."],
        seniority: "Principal",
        employmentType: "Full-time",
        department: "Engineering",
        team: "UI Platform",
        employerWebsiteUrl: "https://northwind.example.com",
        employerDomain: "northwind.example.com",
        benefits: ["Hybrid London team"],
        status: "drafting",
        matchAssessment: {
          score: 88,
          reasons: ["Strong platform overlap"],
          gaps: ["Accessibility leadership"],
        },
        provenance: [],
      },
    ],
    tailoredAssets: [],
    resumeDrafts: [],
    resumeDraftRevisions: [],
    resumeExportArtifacts: [],
    resumeResearchArtifacts: [],
    resumeValidationResults: [],
    resumeAssistantMessages: [],
    applicationRecords: [],
    applicationAttempts: [],
    sourceDebugRuns: [],
    sourceDebugAttempts: [],
    sourceInstructionArtifacts: [],
    sourceDebugEvidenceRefs: [],
    settings: {
      ...emptyState.settings,
      resumeTemplateId: "classic_ats",
      resumeFormat: "pdf",
      fontPreset: "inter_requisite",
      humanReviewRequired: true,
      keepSessionAlive: true,
      allowAutoSubmitOverride: false,
      discoveryOnly: false,
    },
    discovery: {
      sessions: [],
      runState: "idle",
      activeRun: null,
      recentRuns: [],
      activeSourceDebugRun: null,
      recentSourceDebugRuns: [],
      pendingDiscoveryJobs: [],
    },
  });
}
