import {
  JobFinderIntelligenceStateSchema,
  JobFinderSettingsSchema,
  JobSearchPreferencesSchema,
  ProfileSetupStateSchema,
  createFreshStartCandidateProfile,
  createStarterJobDiscoveryTargets,
  type JobFinderRepositoryState,
} from "@unemployed/contracts";

export function createEmptyJobFinderRepositoryState(): JobFinderRepositoryState {
  return {
    // Canonical first-run seed: identity facts stay null until a real value
    // exists, so no instructional placeholder is persisted as a fact.
    profile: createFreshStartCandidateProfile(),
    searchPreferences: JobSearchPreferencesSchema.parse({
      targetRoles: [],
      jobFamilies: [],
      locations: [],
      excludedLocations: [],
      workModes: [],
      seniorityLevels: [],
      minimumSalaryUsd: null,
      targetSalaryUsd: null,
      salaryCurrency: "USD",
      targetIndustries: [],
      targetCompanyStages: [],
      employmentTypes: [],
      approvalMode: "review_before_submit",
      tailoringMode: "balanced",
      companyBlacklist: [],
      companyWhitelist: [],
      discovery: {
        historyLimit: 5,
        // Starter sources give a first-run user understandable choices without
        // requiring URL knowledge. They seed disabled and never enable
        // themselves; setup readiness still requires one explicit enable.
        targets: createStarterJobDiscoveryTargets(),
      },
    }),
    profileSetupState: ProfileSetupStateSchema.parse({
      status: "not_started",
      currentStep: "import",
      completedAt: null,
      reviewItems: [],
      lastResumedAt: null,
    }),
    savedJobs: [],
    tailoredAssets: [],
    resumeDrafts: [],
    resumeDraftRevisions: [],
    resumeExportArtifacts: [],
    resumeResearchArtifacts: [],
    resumeValidationResults: [],
    resumeAssistantMessages: [],
    profileCopilotMessages: [],
    profileRevisions: [],
    applyRuns: [],
    applyJobResults: [],
    applySubmitApprovals: [],
    applicationAuthorityEnvelopes: [],
    submissionPreflights: [],
    submissionExecutionGrants: [],
    submissionIdempotencyRecords: [],
    submissionArmedMarkers: [],
    submissionOutcomeRecords: [],
    applicationQuestionRecords: [],
    applicationAnswerRecords: [],
    applicationArtifactRefs: [],
    applicationReplayCheckpoints: [],
    applicationConsentRequests: [],
    applicationRecords: [],
    applicationAttempts: [],
    userActionRequests: [],
    userActionEvents: [],
    sourceDebugRuns: [],
    sourceDebugAttempts: [],
    sourceInstructionArtifacts: [],
    sourceDebugEvidenceRefs: [],
    resumeImportRuns: [],
    resumeImportDocumentBundles: [],
    resumeImportFieldCandidates: [],
    settings: JobFinderSettingsSchema.parse({
      resumeTemplateId: "classic_ats",
      resumeFormat: "pdf",
      fontPreset: "inter_requisite",
      appearanceTheme: "system",
      humanReviewRequired: true,
      keepSessionAlive: false,
      allowAutoSubmitOverride: false,
      discoveryOnly: false,
    }),
    discovery: {
      sessions: [],
      runState: "idle",
      activeRun: null,
      recentRuns: [],
      activeSourceDebugRun: null,
      recentSourceDebugRuns: [],
      discoveryLedger: [],
      pendingDiscoveryJobs: [],
    },
    campaigns: [],
    activeCampaignId: null,
    campaignNotifications: [],
    activityControl: { paused: false, pausedAt: null, reason: null },
    intelligence: JobFinderIntelligenceStateSchema.parse({}),
  };
}
