import {
  JobFinderRepositoryStateSchema,
  type JobFinderRepositoryState,
} from "@unemployed/contracts";
import { createEmptyJobFinderRepositoryState } from "./job-finder-initial-state";

const demoResumeDraftSections = [
  {
    id: "section_summary",
    kind: "summary",
    label: "Summary",
    text: "Systems-focused product designer with deep workflow automation and design-systems experience.",
    bullets: [],
    entries: [],
    origin: "deterministic_fallback",
    locked: false,
    included: true,
    sortOrder: 0,
    profileRecordId: null,
    sourceRefs: [],
    updatedAt: "2026-03-20T10:04:00.000Z",
  },
  {
    id: "section_experience",
    kind: "experience",
    label: "Experience",
    text: null,
    bullets: [],
    entries: [
      {
        id: "entry_signal_systems",
        entryType: "experience",
        title: "Senior systems designer",
        subtitle: "Signal Systems",
        location: "London, UK",
        dateRange: "2020 - Present",
        summary: "Leads design systems and workflow platform improvements.",
        bullets: [
          {
            id: "bullet_signal_rollout",
            text: "Led design-system rollout across core workflow surfaces used by design and operations teams.",
            origin: "deterministic_fallback",
            locked: false,
            included: true,
            sourceRefs: [],
            updatedAt: "2026-03-20T10:04:00.000Z",
          },
        ],
        origin: "deterministic_fallback",
        locked: false,
        included: true,
        sortOrder: 0,
        profileRecordId: "experience_1",
        sourceRefs: [],
        updatedAt: "2026-03-20T10:04:00.000Z",
      },
    ],
    origin: "deterministic_fallback",
    locked: false,
    included: true,
    sortOrder: 1,
    profileRecordId: null,
    sourceRefs: [],
    updatedAt: "2026-03-20T10:04:00.000Z",
  },
] as const;

export function createResumeWorkspaceDemoState(): JobFinderRepositoryState {
  const emptyState = createEmptyJobFinderRepositoryState();

  return JobFinderRepositoryStateSchema.parse({
    ...emptyState,
    profile: {
      ...emptyState.profile,
      id: "candidate_1",
      firstName: "Alex",
      lastName: "Vanguard",
      fullName: "Alex Vanguard",
      headline: "Senior systems designer",
      summary: "Builds resilient workflows for design systems, workflow automation, and operations platforms.",
      currentLocation: "London, UK",
      yearsExperience: 10,
      email: "alex@example.com",
      phone: "+44 7700 900123",
      portfolioUrl: "https://alex.example.com",
      linkedinUrl: "https://www.linkedin.com/in/alex-vanguard",
      narrative: {
        professionalStory:
          "Design systems and workflow tooling leader who turns messy multi-team operations into clear product systems.",
        nextChapterSummary:
          "Looking for remote product-design roles that combine systems thinking, workflow automation, and cross-functional leadership.",
        careerTransitionSummary:
          "Open to roles that bridge product design and workflow platform ownership because that has been the strongest throughline of recent work.",
        differentiators: [
          "Turns ambiguous workflow pain into durable design systems",
          "Pairs product strategy with hands-on systems execution",
        ],
        motivationThemes: ["workflow automation", "design systems", "platform quality"],
      },
      proofBank: [
        {
          id: "proof_1",
          title: "Design-system rollout",
          claim: "Led a design-system rollout across core workflow surfaces used by design and operations teams.",
          heroMetric: "Adoption reached 80% of core product surfaces within two quarters.",
          supportingContext:
            "Worked across product, engineering, and operations to standardize interaction and content patterns.",
          roleFamilies: ["product design", "design systems", "platform"],
          projectIds: [],
          linkIds: ["link_1"],
        },
      ],
      answerBank: {
        workAuthorization: "Authorized to work in the United Kingdom and open to remote roles across Europe.",
        visaSponsorship: "Do not currently require visa sponsorship for UK-based roles.",
        relocation: "Open to relocation for the right platform or systems role.",
        travel: "Open to occasional travel for planning, workshops, and launch support.",
        noticePeriod: "Currently able to start after a 30-day notice period.",
        availability: "Available to interview now and start within 30 days.",
        salaryExpectations: "Targeting senior remote roles in the 180k-220k USD range depending on scope and package.",
        selfIntroduction:
          "I am a systems-focused product designer with 10 years of experience building workflow tools, design systems, and cross-functional operating rhythms.",
        careerTransition:
          "I am leaning further into systems and workflow platform roles because that is where my strongest measurable impact has been.",
        customAnswers: [],
      },
      applicationIdentity: {
        preferredEmail: "alex@example.com",
        preferredPhone: "+44 7700 900123",
        preferredLinkIds: ["link_1"],
      },
      baseResume: {
        ...emptyState.profile.baseResume,
        id: "resume_1",
        fileName: "alex-vanguard.pdf",
        uploadedAt: "2026-03-20T10:00:00.000Z",
        storagePath: "/tmp/alex-vanguard.pdf",
        textContent:
          "Alex Vanguard\nSenior systems designer\nLondon, UK\nalex@example.com\n+44 7700 900123\nhttps://alex.example.com\nhttps://www.linkedin.com/in/alex-vanguard\n\n10 years of experience building resilient workflow tools with Figma, React, and design systems.",
        textUpdatedAt: "2026-03-20T10:00:00.000Z",
        extractionStatus: "ready",
        lastAnalyzedAt: "2026-03-20T10:01:00.000Z",
        analysisWarnings: [],
      },
      targetRoles: ["Principal Designer"],
      locations: ["Remote"],
      skills: ["Figma", "React", "Design Systems"],
      experiences: [
        {
          id: "experience_1",
          companyName: "Signal Systems",
          companyUrl: null,
          title: "Senior systems designer",
          employmentType: "Full-time",
          location: "London, UK",
          workMode: ["hybrid"],
          startDate: "2020-01",
          endDate: null,
          isCurrent: true,
          isDraft: false,
          summary: "Builds resilient workflow tools.",
          achievements: ["Led design-system rollout across core workflow surfaces."],
          skills: ["Figma", "Design Systems"],
          domainTags: [],
          peopleManagementScope: null,
          ownershipScope: null,
        },
      ],
      education: [
        {
          id: "education_1",
          schoolName: "Royal College of Art",
          degree: "MA",
          fieldOfStudy: "Design Products",
          location: "London, UK",
          startDate: "2012-09",
          endDate: "2014-06",
          isDraft: false,
          summary: null,
        },
      ],
      links: [
        {
          id: "link_1",
          label: "Portfolio",
          url: "https://alex.example.com",
          kind: "portfolio",
          isDraft: false,
        },
      ],
    },
    searchPreferences: {
      ...emptyState.searchPreferences,
      targetRoles: [
        "Principal Designer",
        "Senior Product Designer",
        "Principal UX Engineer",
      ],
      locations: ["Remote", "London"],
      workModes: ["remote", "hybrid"],
      seniorityLevels: ["senior"],
      minimumSalaryUsd: 170000,
      salaryCurrency: "USD",
      companyWhitelist: ["Signal Systems"],
      discovery: {
        historyLimit: 5,
        targets: [
          {
            id: "target_linkedin_default",
            label: "Primary target",
            startingUrl: "https://www.linkedin.com/jobs/search/",
            enabled: true,
            adapterKind: "auto",
            customInstructions: null,
            instructionStatus: "missing",
            validatedInstructionId: null,
            draftInstructionId: null,
            lastDebugRunId: null,
            lastVerifiedAt: null,
            staleReason: null,
          },
        ],
      },
    },
    savedJobs: [
      {
        id: "job_ready",
        source: "target_site",
        sourceJobId: "linkedin_signal_ready",
        discoveryMethod: "catalog_seed",
        canonicalUrl: "https://www.linkedin.com/jobs/view/linkedin_signal_ready",
        applicationUrl: "https://www.linkedin.com/jobs/view/linkedin_signal_ready/apply",
        title: "Senior Product Designer",
        company: "Signal Systems",
        location: "Remote",
        workMode: ["remote"],
        applyPath: "easy_apply",
        easyApplyEligible: true,
        postedAt: "2026-03-20T09:00:00.000Z",
        postedAtText: null,
        discoveredAt: "2026-03-20T09:05:00.000Z",
        firstSeenAt: "2026-03-20T09:05:00.000Z",
        lastSeenAt: "2026-03-20T09:05:00.000Z",
        lastVerifiedActiveAt: "2026-03-20T09:05:00.000Z",
        salaryText: "$180k - $220k",
        normalizedCompensation: {
          currency: "USD",
          interval: "year",
          minAmount: 180000,
          maxAmount: 220000,
          minAnnualUsd: 180000,
          maxAnnualUsd: 220000,
        },
        summary: "Own the design system.",
        description: "Own the design system and workflow platform.",
        keySkills: ["Figma", "Design Systems"],
        responsibilities: ["Own the design system roadmap."],
        minimumQualifications: ["Strong product design systems experience."],
        preferredQualifications: ["Workflow-platform product background."],
        seniority: "Senior",
        employmentType: "Full-time",
        department: "Design",
        team: "Design Systems",
        employerWebsiteUrl: "https://signalsystems.example.com",
        employerDomain: "signalsystems.example.com",
        atsProvider: null,
        screeningHints: {
          sponsorshipText: null,
          requiresSecurityClearance: null,
          relocationText: null,
          travelText: null,
          remoteGeographies: ["Europe"],
        },
        keywordSignals: [
          {
            id: "job_ready_signal_design_systems",
            label: "Design Systems",
            kind: "skill",
            weight: 5,
          },
          {
            id: "job_ready_signal_workflow_platform",
            label: "Workflow platform",
            kind: "domain",
            weight: 4,
          },
        ],
        benefits: ["Remote-first collaboration"],
        status: "ready_for_review",
        matchAssessment: {
          score: 96,
          reasons: ["Strong design-systems overlap"],
          gaps: [],
        },
        provenance: [],
      },
      {
        id: "job_generating",
        source: "target_site",
        sourceJobId: "linkedin_northwind_generating",
        discoveryMethod: "catalog_seed",
        canonicalUrl: "https://www.linkedin.com/jobs/view/linkedin_northwind_generating",
        applicationUrl: null,
        title: "Principal UX Engineer",
        company: "Northwind Labs",
        location: "Hybrid, London",
        workMode: ["hybrid"],
        applyPath: "easy_apply",
        easyApplyEligible: true,
        postedAt: "2026-03-20T08:00:00.000Z",
        postedAtText: null,
        discoveredAt: "2026-03-20T08:05:00.000Z",
        firstSeenAt: "2026-03-20T08:05:00.000Z",
        lastSeenAt: "2026-03-20T08:05:00.000Z",
        lastVerifiedActiveAt: "2026-03-20T08:05:00.000Z",
        salaryText: "$175k - $205k",
        normalizedCompensation: {
          currency: "USD",
          interval: "year",
          minAmount: 175000,
          maxAmount: 205000,
          minAnnualUsd: 175000,
          maxAnnualUsd: 205000,
        },
        summary: "Lead cross-functional UI platform work.",
        description:
          "Lead cross-functional UI platform work with portfolio review required.",
        keySkills: ["React"],
        responsibilities: ["Lead UI platform architecture."],
        minimumQualifications: ["Deep React experience."],
        preferredQualifications: ["Accessibility leadership experience."],
        seniority: "Principal",
        employmentType: "Full-time",
        department: "Engineering",
        team: "UI Platform",
        employerWebsiteUrl: "https://northwind.example.com",
        employerDomain: "northwind.example.com",
        atsProvider: null,
        screeningHints: {
          sponsorshipText: null,
          requiresSecurityClearance: null,
          relocationText: null,
          travelText: null,
          remoteGeographies: [],
        },
        keywordSignals: [
          {
            id: "job_generating_react",
            label: "React",
            kind: "skill",
            weight: 5,
          },
          {
            id: "job_generating_portfolio",
            label: "Portfolio review",
            kind: "qualification",
            weight: 3,
          },
        ],
        benefits: ["Hybrid London team"],
        status: "drafting",
        matchAssessment: {
          score: 88,
          reasons: ["Strong platform overlap"],
          gaps: ["Accessibility leadership"],
        },
        provenance: [],
      },
    ],
    tailoredAssets: [],
    resumeDrafts: [],
    resumeDraftRevisions: [],
    resumeExportArtifacts: [],
    resumeResearchArtifacts: [],
    resumeValidationResults: [],
    resumeAssistantMessages: [],
    applicationRecords: [],
    applicationAttempts: [],
    sourceDebugRuns: [],
    sourceDebugAttempts: [],
    sourceInstructionArtifacts: [],
    sourceDebugEvidenceRefs: [],
    resumeImportRuns: [],
    resumeImportDocumentBundles: [],
    resumeImportFieldCandidates: [],
    settings: {
      ...emptyState.settings,
      resumeTemplateId: "classic_ats",
      resumeFormat: "pdf",
      fontPreset: "inter_requisite",
      appearanceTheme: "system",
      humanReviewRequired: true,
      keepSessionAlive: true,
      allowAutoSubmitOverride: false,
      discoveryOnly: false,
    },
    discovery: {
      sessions: [],
      runState: "idle",
      activeRun: null,
      recentRuns: [],
      activeSourceDebugRun: null,
      recentSourceDebugRuns: [],
      pendingDiscoveryJobs: [],
    },
  });
}

export function createApplyQueueDemoState(): JobFinderRepositoryState {
  const resumeDemoState = createResumeWorkspaceDemoState();
  const readySavedJob = resumeDemoState.savedJobs.find((job) => job.id === "job_ready");
  const generatingSavedJob = resumeDemoState.savedJobs.find(
    (job) => job.id === "job_generating",
  );

  if (!readySavedJob || !generatingSavedJob) {
    throw new Error("Resume workspace demo state is missing required saved jobs.");
  }

  return JobFinderRepositoryStateSchema.parse({
    ...resumeDemoState,
    savedJobs: [
      readySavedJob,
      {
        ...readySavedJob,
        id: "job_consent_queue",
        sourceJobId: "linkedin_consent_queue",
        canonicalUrl: "https://www.linkedin.com/jobs/view/linkedin_consent_queue",
        applicationUrl:
          "https://www.linkedin.com/jobs/view/linkedin_consent_queue/apply",
        title: "Staff Product Designer",
        company: "Consent Labs",
        summary: "Guide a workflow platform that pauses on account-consent questions.",
        description:
          "Guide a workflow platform that asks whether you already have an account before continuing the application.",
        keywordSignals: [
          {
            id: "job_consent_queue_consent_gate",
            label: "Existing account decision",
            kind: "qualification",
            weight: 4,
          },
        ],
        screeningHints: {
          ...readySavedJob.screeningHints,
          requiresConsentInterrupt: true,
          requiresConsentInterruptKind: "existing_account_decision",
        },
        status: "ready_for_review",
        matchAssessment: {
          score: 93,
          reasons: ["Strong workflow automation overlap"],
          gaps: [],
        },
      },
      {
        ...generatingSavedJob,
        id: "job_not_ready_queue",
        sourceJobId: "linkedin_not_ready_queue",
        canonicalUrl: "https://www.linkedin.com/jobs/view/linkedin_not_ready_queue",
        applicationUrl:
          "https://www.linkedin.com/jobs/view/linkedin_not_ready_queue/apply",
        title: "Lead UX Strategist",
        company: "Northwind Labs",
        status: "ready_for_review",
      },
    ],
    tailoredAssets: [
      {
        id: "asset_job_ready",
        jobId: "job_ready",
        kind: "resume",
        status: "ready",
        label: "Tailored Resume",
        version: "v1",
        templateName: "Classic ATS",
        compatibilityScore: 96,
        progressPercent: 100,
        updatedAt: "2026-03-20T10:04:00.000Z",
        storagePath: "/tmp/job-ready-resume.pdf",
        contentText: "Ready tailored resume for job_ready",
        previewSections: [],
        generationMethod: "deterministic",
        notes: [],
      },
      {
        id: "asset_job_consent_queue",
        jobId: "job_consent_queue",
        kind: "resume",
        status: "ready",
        label: "Tailored Resume",
        version: "v1",
        templateName: "Classic ATS",
        compatibilityScore: 95,
        progressPercent: 100,
        updatedAt: "2026-03-20T10:04:00.000Z",
        storagePath: "/tmp/job-consent-queue-resume.pdf",
        contentText: "Ready tailored resume for job_consent_queue",
        previewSections: [],
        generationMethod: "deterministic",
        notes: [],
      },
    ],
    resumeDrafts: [
      {
        id: "resume_draft_job_ready",
        jobId: "job_ready",
        status: "approved",
        templateId: "classic_ats",
        sections: demoResumeDraftSections,
        targetPageCount: 2,
        generationMethod: "deterministic",
        approvedAt: "2026-03-20T10:04:00.000Z",
        approvedExportId: "resume_export_job_ready",
        staleReason: null,
        createdAt: "2026-03-20T10:00:00.000Z",
        updatedAt: "2026-03-20T10:04:00.000Z",
      },
      {
        id: "resume_draft_job_consent_queue",
        jobId: "job_consent_queue",
        status: "approved",
        templateId: "classic_ats",
        sections: demoResumeDraftSections,
        targetPageCount: 2,
        generationMethod: "deterministic",
        approvedAt: "2026-03-20T10:04:00.000Z",
        approvedExportId: "resume_export_job_consent_queue",
        staleReason: null,
        createdAt: "2026-03-20T10:00:00.000Z",
        updatedAt: "2026-03-20T10:04:00.000Z",
      },
    ],
    resumeExportArtifacts: [
      {
        id: "resume_export_job_ready",
        draftId: "resume_draft_job_ready",
        jobId: "job_ready",
        format: "pdf",
        filePath: "/tmp/job-ready-resume.pdf",
        pageCount: 2,
        templateId: "classic_ats",
        exportedAt: "2026-03-20T10:04:00.000Z",
        isApproved: true,
      },
      {
        id: "resume_export_job_consent_queue",
        draftId: "resume_draft_job_consent_queue",
        jobId: "job_consent_queue",
        format: "pdf",
        filePath: "/tmp/job-consent-queue-resume.pdf",
        pageCount: 2,
        templateId: "classic_ats",
        exportedAt: "2026-03-20T10:04:00.000Z",
        isApproved: true,
      },
    ],
  });
}
