import { describe, expect, test } from "vitest";
import {
  ApplicationAttemptSchema,
  JobFinderWorkspaceSnapshotSchema,
} from "./index";
import { createSubmittedAttempt } from "./test-fixtures";

describe("contracts workspace snapshot schema", () => {
  test("parses a job finder workspace snapshot", () => {
    const attempt = ApplicationAttemptSchema.parse(createSubmittedAttempt());

    const workspace = JobFinderWorkspaceSnapshotSchema.parse({
      module: "job-finder",
      generatedAt: "2026-03-20T10:05:00.000Z",
      agentProvider: {
        kind: "deterministic",
        ready: true,
        label: "Built-in deterministic agent fallback",
        model: null,
        baseUrl: null,
        detail: "Tests",
      },
      availableResumeTemplates: [
        {
          id: "classic_ats",
          label: "Classic ATS",
          description: "Single-column and ATS-friendly.",
        },
      ],
      profile: {
        id: "candidate_1",
        firstName: "Alex",
        lastName: "Vanguard",
        middleName: null,
        fullName: "Alex Vanguard",
        headline: "Senior systems designer",
        summary: "Builds resilient workflows.",
        currentLocation: "London, UK",
        yearsExperience: 10,
        email: "alex@example.com",
        phone: null,
        portfolioUrl: null,
        linkedinUrl: null,
        baseResume: {
          id: "resume_1",
          fileName: "alex-vanguard.pdf",
          uploadedAt: "2026-03-20T10:00:00.000Z",
          storagePath: "/tmp/alex-vanguard.pdf",
          textContent: "Resume text",
          textUpdatedAt: "2026-03-20T10:00:00.000Z",
          extractionStatus: "ready",
          lastAnalyzedAt: "2026-03-20T10:01:00.000Z",
          analysisProviderKind: null,
          analysisProviderLabel: null,
          analysisWarnings: [],
        },
        targetRoles: ["Principal Designer"],
        locations: ["Remote"],
        skills: ["Figma", "React"],
        experiences: [
          {
            id: "experience_1",
            companyName: "Signal Systems",
            companyUrl: null,
            title: "Senior Product Designer",
            employmentType: "Full-time",
            location: "London, UK",
            workMode: "hybrid",
            startDate: "2021-01",
            endDate: null,
            isCurrent: true,
            summary: "Owns workflow tooling and design systems.",
            achievements: ["Improved designer-engineer handoff quality"],
            skills: ["Figma", "Design Systems"],
            domainTags: [],
            peopleManagementScope: null,
            ownershipScope: null,
          },
        ],
        education: [
          {
            id: "education_1",
            schoolName: "University of the Arts London",
            degree: "BA",
            fieldOfStudy: "Interaction Design",
            location: "London, UK",
            startDate: "2010-09",
            endDate: "2013-06",
            summary: null,
          },
        ],
        certifications: [
          {
            id: "certification_1",
            name: "UX Certification",
            issuer: "NN/g",
            issueDate: "2020-04",
            expiryDate: null,
            credentialUrl: null,
          },
        ],
        links: [
          {
            id: "link_1",
            label: "Portfolio",
            url: "https://alex.example.com",
            kind: "portfolio",
          },
        ],
        projects: [],
        spokenLanguages: [],
      },
      searchPreferences: {
        targetRoles: ["Principal Designer"],
        jobFamilies: [],
        locations: ["Remote"],
        excludedLocations: [],
        workModes: ["remote"],
        seniorityLevels: ["senior"],
        targetIndustries: [],
        targetCompanyStages: [],
        employmentTypes: [],
        minimumSalaryUsd: 170000,
        targetSalaryUsd: null,
        salaryCurrency: "USD",
        approvalMode: "review_before_submit",
        tailoringMode: "balanced",
        companyBlacklist: [],
        companyWhitelist: [],
      },
      browserSession: {
        source: "target_site",
        status: "ready",
        driver: "catalog_seed",
        label: "Browser session ready",
        detail: "Validated recently.",
        lastCheckedAt: "2026-03-20T10:04:00.000Z",
      },
      discoveryJobs: [
        {
          id: "job_1",
          source: "target_site",
          sourceJobId: "target_job_1",
          discoveryMethod: "catalog_seed",
          canonicalUrl: "https://jobs.example.com/roles/target_job_1",
          title: "Senior Product Designer",
          company: "Signal Systems",
          location: "Remote",
          workMode: "remote",
          applyPath: "easy_apply",
          easyApplyEligible: true,
          postedAt: "2026-03-20T09:00:00.000Z",
          postedAtText: null,
          discoveredAt: "2026-03-20T10:01:00.000Z",
          salaryText: "$180k - $220k",
          summary: "Own the design system.",
          description: "Own the design system and workflow platform.",
          keySkills: ["Figma"],
          responsibilities: [],
          minimumQualifications: [],
          preferredQualifications: [],
          seniority: null,
          employmentType: null,
          department: null,
          team: null,
          employerWebsiteUrl: null,
          employerDomain: null,
          benefits: [],
          status: "ready_for_review",
          matchAssessment: {
            score: 96,
            reasons: ["Strong product design overlap"],
            gaps: [],
          },
        },
      ],
      activeSourceDebugRun: {
        id: "source_debug_run_1",
        targetId: "target_1",
        state: "paused_manual",
        startedAt: "2026-03-20T10:00:00.000Z",
        updatedAt: "2026-03-20T10:01:00.000Z",
        completedAt: "2026-03-20T10:01:00.000Z",
        activePhase: "access_auth_probe",
        phases: [
          "access_auth_probe",
          "site_structure_mapping",
          "search_filter_probe",
          "job_detail_validation",
          "apply_path_validation",
          "replay_verification",
        ],
        targetLabel: "KosovaJob",
        targetUrl: "https://kosovajob.com/",
        targetHostname: "kosovajob.com",
        manualPrerequisiteSummary: "Please sign in first.",
        finalSummary: "Manual login is required before debugging can continue.",
        attemptIds: ["source_debug_attempt_1"],
        phaseSummaries: [],
        instructionArtifactId: null,
      },
      recentSourceDebugRuns: [],
      selectedDiscoveryJobId: "job_1",
      reviewQueue: [
        {
          jobId: "job_1",
          title: "Senior Product Designer",
          company: "Signal Systems",
          location: "Remote",
          matchScore: 96,
          applicationStatus: "ready_for_review",
          assetStatus: "ready",
          progressPercent: 100,
          resumeAssetId: "asset_1",
          resumeReview: {
            status: "approved",
            approvedAt: "2026-03-20T10:03:30.000Z",
            approvedExportId: "resume_export_1",
            approvedFormat: "pdf",
            approvedFilePath: "/tmp/alex-signal.pdf",
          },
          updatedAt: "2026-03-20T10:03:00.000Z",
        },
      ],
      selectedReviewJobId: "job_1",
      tailoredAssets: [
        {
          id: "asset_1",
          jobId: "job_1",
          kind: "resume",
          status: "ready",
          label: "Tailored Resume",
          version: "v1",
          templateName: "Classic ATS",
          compatibilityScore: 98,
          progressPercent: 100,
          updatedAt: "2026-03-20T10:03:00.000Z",
          storagePath: null,
          contentText: "Tailored resume body",
          generationMethod: "ai_assisted",
          notes: ["Generated from stored resume text."],
          previewSections: [
            {
              heading: "Summary",
              lines: ["Lead cross-functional UX systems work."],
            },
          ],
        },
      ],
      resumeDrafts: [
        {
          id: "resume_draft_1",
          jobId: "job_1",
          status: "approved",
          templateId: "classic_ats",
          targetPageCount: 2,
          generationMethod: "ai",
          approvedAt: "2026-03-20T10:03:30.000Z",
          approvedExportId: "resume_export_1",
          staleReason: null,
          createdAt: "2026-03-20T10:02:00.000Z",
          updatedAt: "2026-03-20T10:03:30.000Z",
        },
      ],
      resumeExportArtifacts: [
        {
          id: "resume_export_1",
          draftId: "resume_draft_1",
          jobId: "job_1",
          format: "pdf",
          filePath: "/tmp/alex-signal.pdf",
          pageCount: 2,
          templateId: "classic_ats",
          exportedAt: "2026-03-20T10:03:10.000Z",
          isApproved: true,
        },
      ],
      resumeResearchArtifacts: [
        {
          id: "resume_research_1",
          jobId: "job_1",
          sourceUrl: "https://signalsystems.example.com/about",
          pageTitle: "About Signal Systems",
          fetchedAt: "2026-03-20T10:01:30.000Z",
          fetchStatus: "success",
          domainVocabulary: ["workflow platform"],
          priorityThemes: ["design systems"],
        },
      ],
      applicationRecords: [
        {
          id: "application_1",
          jobId: "job_5",
          title: "Lead Product Designer",
          company: "Northwind Labs",
          status: "interview",
          lastActionLabel: "Technical screen scheduled",
          nextActionLabel: "Join meeting",
          lastUpdatedAt: "2026-03-20T10:04:00.000Z",
          lastAttemptState: "submitted",
          events: [
            {
              id: "event_1",
              at: "2026-03-20T10:04:00.000Z",
              title: "Technical screen scheduled",
              detail: "Interview confirmed for tomorrow.",
              emphasis: "positive",
            },
          ],
        },
      ],
      applicationAttempts: [attempt],
      selectedApplicationRecordId: "application_1",
      settings: {
        resumeFormat: "html",
        resumeTemplateId: "classic_ats",
        fontPreset: "inter_requisite",
        appearanceTheme: "system",
        humanReviewRequired: true,
        allowAutoSubmitOverride: false,
        keepSessionAlive: true,
      },
    });

    expect(workspace.discoveryJobs).toHaveLength(1);
    expect(workspace.profile.experiences[0]?.workMode).toEqual(["hybrid"]);
    expect(workspace.discoveryJobs[0]?.workMode).toEqual(["remote"]);
    expect(workspace.reviewQueue[0]?.assetStatus).toBe("ready");
    expect(workspace.applicationAttempts[0]?.state).toBe("submitted");
    expect(workspace.activeSourceDebugRun?.state).toBe("paused_manual");
  });
});
