import type { FieldDescriptor } from "./profile-copilot-field-updates-shared";
import {
  parseNullableList,
  parseNullableText,
  parseRequiredText,
} from "./profile-copilot-field-updates-shared";

export const profileFieldDescriptors: ReadonlyArray<FieldDescriptor<unknown>> = [
  {
    aliases: ["preferred display name", "preferred name", "display name"],
    applyMode: "applied",
    key: "preferredDisplayName",
    operation: "replace_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.preferredDisplayName,
    reviewDomain: "identity",
    title: "preferred display name",
  },
  {
    aliases: ["secondary email", "backup email"],
    applyMode: "applied",
    key: "secondaryEmail",
    operation: "replace_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.secondaryEmail,
    reviewDomain: "identity",
    title: "secondary email",
  },
  {
    aliases: ["first name", "given name"],
    applyMode: "applied",
    key: "firstName",
    operation: "replace_identity_fields",
    parseValue: (detail) => parseRequiredText(detail),
    readCurrentValue: (input) => input.profile.firstName,
    reviewDomain: "identity",
    title: "first name",
  },
  {
    aliases: ["middle name"],
    applyMode: "applied",
    key: "middleName",
    operation: "replace_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.middleName,
    reviewDomain: "identity",
    title: "middle name",
  },
  {
    aliases: ["last name", "surname", "family name"],
    applyMode: "applied",
    key: "lastName",
    operation: "replace_identity_fields",
    parseValue: (detail) => parseRequiredText(detail),
    readCurrentValue: (input) => input.profile.lastName,
    reviewDomain: "identity",
    title: "last name",
  },
  {
    aliases: ["email", "main email"],
    applyMode: "applied",
    key: "email",
    operation: "replace_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.email,
    reviewDomain: "identity",
    title: "email",
  },
  {
    aliases: ["phone", "phone number"],
    applyMode: "applied",
    key: "phone",
    operation: "replace_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.phone,
    reviewDomain: "identity",
    title: "phone",
  },
  {
    aliases: ["current city", "city"],
    applyMode: "applied",
    key: "currentCity",
    operation: "replace_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.currentCity,
    reviewDomain: "identity",
    title: "current city",
  },
  {
    aliases: ["current region", "region", "state", "province"],
    applyMode: "applied",
    key: "currentRegion",
    operation: "replace_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.currentRegion,
    reviewDomain: "identity",
    title: "current region",
  },
  {
    aliases: ["current country", "country"],
    applyMode: "applied",
    key: "currentCountry",
    operation: "replace_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.currentCountry,
    reviewDomain: "identity",
    title: "current country",
  },
  {
    aliases: ["current location", "displayed location"],
    applyMode: "applied",
    key: "currentLocation",
    operation: "replace_identity_fields",
    parseValue: (detail) => parseRequiredText(detail),
    readCurrentValue: (input) => input.profile.currentLocation,
    reviewDomain: "identity",
    title: "displayed location",
  },
  {
    aliases: ["time zone", "timezone"],
    applyMode: "applied",
    key: "timeZone",
    operation: "replace_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.timeZone,
    reviewDomain: "identity",
    title: "time zone",
  },
  {
    aliases: ["headline"],
    applyMode: "applied",
    key: "headline",
    operation: "replace_identity_fields",
    parseValue: (detail) => parseRequiredText(detail),
    readCurrentValue: (input) => input.profile.headline,
    reviewDomain: "identity",
    title: "headline",
  },
  {
    aliases: ["profile summary", "summary", "bio"],
    applyMode: "applied",
    key: "summary",
    operation: "replace_identity_fields",
    parseValue: (detail) => parseRequiredText(detail),
    readCurrentValue: (input) => input.profile.summary,
    reviewDomain: "identity",
    title: "summary",
  },
  {
    aliases: ["profile skills", "skills list", "overall skills"],
    applyMode: "applied",
    key: "skills",
    operation: "replace_profile_list_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.skills,
    reviewDomain: null,
    title: "skills",
  },
];
