import type { FieldDescriptor } from "./profile-copilot-field-updates-shared";
import {
  parseApprovalMode,
  parseNullableBoolean,
  parseNullableInteger,
  parseNullableList,
  parseNullableText,
  parseSalaryCurrency,
  parseTailoringMode,
} from "./profile-copilot-field-updates-shared";
import { requestLooksLikeLocationListEdit } from "./profile-copilot-helpers";

export const preferenceFieldDescriptors: ReadonlyArray<FieldDescriptor<unknown>> = [
  {
    aliases: ["authorized work countries", "work countries", "countries i can work in"],
    applyMode: "needs_review",
    key: "authorizedWorkCountries",
    operation: "replace_work_eligibility_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.workEligibility.authorizedWorkCountries,
    reviewDomain: "work_eligibility",
    title: "authorized work countries",
  },
  {
    aliases: ["willing to relocate", "relocation preference"],
    applyMode: "applied",
    key: "willingToRelocate",
    operation: "replace_work_eligibility_fields",
    parseValue: parseNullableBoolean,
    readCurrentValue: (input) => input.profile.workEligibility.willingToRelocate,
    reviewDomain: "work_eligibility",
    title: "relocation preference",
  },
  {
    aliases: ["preferred relocation regions", "relocation regions", "relocation locations"],
    applyMode: "needs_review",
    key: "preferredRelocationRegions",
    operation: "replace_work_eligibility_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.workEligibility.preferredRelocationRegions,
    reviewDomain: "work_eligibility",
    title: "preferred relocation regions",
  },
  {
    aliases: ["willing to travel", "travel preference"],
    applyMode: "applied",
    key: "willingToTravel",
    operation: "replace_work_eligibility_fields",
    parseValue: parseNullableBoolean,
    readCurrentValue: (input) => input.profile.workEligibility.willingToTravel,
    reviewDomain: "work_eligibility",
    title: "travel preference",
  },
  {
    aliases: ["available start date", "start date"],
    applyMode: "applied",
    key: "availableStartDate",
    operation: "replace_work_eligibility_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.workEligibility.availableStartDate,
    reviewDomain: "work_eligibility",
    title: "available start date",
  },
  {
    aliases: ["notice period days", "notice period in days"],
    applyMode: "applied",
    key: "noticePeriodDays",
    operation: "replace_work_eligibility_fields",
    parseValue: parseNullableInteger,
    readCurrentValue: (input) => input.profile.workEligibility.noticePeriodDays,
    reviewDomain: "work_eligibility",
    title: "notice period days",
  },
  {
    aliases: ["security clearance", "clearance"],
    applyMode: "applied",
    key: "securityClearance",
    operation: "replace_work_eligibility_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.workEligibility.securityClearance,
    reviewDomain: "work_eligibility",
    title: "security clearance",
  },
  {
    aliases: ["preferred application email", "preferred email"],
    applyMode: "applied",
    key: "preferredEmail",
    matchesRequest: (normalizedRequest) =>
      /preferred application email/.test(normalizedRequest) ||
      /preferred email/.test(normalizedRequest),
    operation: "replace_application_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.applicationIdentity.preferredEmail,
    reviewDomain: null,
    title: "preferred application email",
  },
  {
    aliases: ["preferred application phone", "preferred phone"],
    applyMode: "applied",
    key: "preferredPhone",
    matchesRequest: (normalizedRequest) =>
      /preferred application phone/.test(normalizedRequest) ||
      /preferred phone/.test(normalizedRequest),
    operation: "replace_application_identity_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.applicationIdentity.preferredPhone,
    reviewDomain: null,
    title: "preferred application phone",
  },
  {
    aliases: ["preferred public link ids", "preferred link ids"],
    applyMode: "needs_review",
    key: "preferredLinkIds",
    operation: "replace_application_identity_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.applicationIdentity.preferredLinkIds,
    reviewDomain: null,
    title: "preferred public link IDs",
  },
  {
    aliases: ["highlighted skills"],
    applyMode: "applied",
    key: "highlightedSkills",
    operation: "replace_skill_group_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.skillGroups.highlightedSkills,
    reviewDomain: null,
    title: "highlighted skills",
  },
  {
    aliases: ["languages and frameworks", "frameworks"],
    applyMode: "applied",
    key: "languagesAndFrameworks",
    operation: "replace_skill_group_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.skillGroups.languagesAndFrameworks,
    reviewDomain: null,
    title: "languages and frameworks",
  },
  {
    aliases: ["soft skills"],
    applyMode: "applied",
    key: "softSkills",
    operation: "replace_skill_group_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.skillGroups.softSkills,
    reviewDomain: null,
    title: "soft skills",
  },
  {
    aliases: ["core skills"],
    applyMode: "applied",
    key: "coreSkills",
    matchesRequest: (normalizedRequest) => /core skills/.test(normalizedRequest),
    operation: "replace_skill_group_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.skillGroups.coreSkills,
    reviewDomain: null,
    title: "core skills",
  },
  {
    aliases: ["tools"],
    applyMode: "applied",
    key: "tools",
    operation: "replace_skill_group_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.skillGroups.tools,
    reviewDomain: null,
    title: "tools",
  },
  {
    aliases: ["preferred locations", "locations to search", "target locations"],
    applyMode: "needs_review",
    key: "locations",
    matchesRequest: requestLooksLikeLocationListEdit,
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.searchPreferences.locations,
    reviewDomain: "search_preferences",
    title: "preferred locations",
  },
  {
    aliases: ["excluded locations"],
    applyMode: "needs_review",
    key: "excludedLocations",
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.searchPreferences.excludedLocations,
    reviewDomain: "search_preferences",
    title: "excluded locations",
  },
  {
    aliases: ["job families"],
    applyMode: "needs_review",
    key: "jobFamilies",
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.searchPreferences.jobFamilies,
    reviewDomain: "search_preferences",
    title: "job families",
  },
  {
    aliases: ["seniority levels", "seniority"],
    applyMode: "needs_review",
    key: "seniorityLevels",
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.searchPreferences.seniorityLevels,
    reviewDomain: "search_preferences",
    title: "seniority levels",
  },
  {
    aliases: ["target industries", "industries"],
    applyMode: "needs_review",
    key: "targetIndustries",
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.searchPreferences.targetIndustries,
    reviewDomain: "search_preferences",
    title: "target industries",
  },
  {
    aliases: ["target company stages", "company stages"],
    applyMode: "needs_review",
    key: "targetCompanyStages",
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.searchPreferences.targetCompanyStages,
    reviewDomain: "search_preferences",
    title: "target company stages",
  },
  {
    aliases: ["employment types", "employment type preferences"],
    applyMode: "needs_review",
    key: "employmentTypes",
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.searchPreferences.employmentTypes,
    reviewDomain: "search_preferences",
    title: "employment types",
  },
  {
    aliases: ["minimum salary"],
    applyMode: "applied",
    key: "minimumSalaryUsd",
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableInteger,
    readCurrentValue: (input) => input.searchPreferences.minimumSalaryUsd,
    reviewDomain: "search_preferences",
    title: "minimum salary",
  },
  {
    aliases: ["salary currency", "currency"],
    applyMode: "applied",
    key: "salaryCurrency",
    operation: "replace_search_preferences_fields",
    parseValue: parseSalaryCurrency,
    readCurrentValue: (input) => input.searchPreferences.salaryCurrency,
    reviewDomain: "search_preferences",
    title: "salary currency",
  },
  {
    aliases: ["tailoring mode", "resume tailoring style", "tailoring style"],
    applyMode: "applied",
    key: "tailoringMode",
    operation: "replace_search_preferences_fields",
    parseValue: parseTailoringMode,
    readCurrentValue: (input) => input.searchPreferences.tailoringMode,
    reviewDomain: "search_preferences",
    title: "default resume tailoring style",
  },
  {
    aliases: ["approval mode", "submit approval mode"],
    applyMode: "needs_review",
    key: "approvalMode",
    operation: "replace_search_preferences_fields",
    parseValue: parseApprovalMode,
    readCurrentValue: (input) => input.searchPreferences.approvalMode,
    reviewDomain: "search_preferences",
    title: "approval mode",
  },
  {
    aliases: ["company blacklist", "blocked companies"],
    applyMode: "needs_review",
    key: "companyBlacklist",
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.searchPreferences.companyBlacklist,
    reviewDomain: "search_preferences",
    title: "company blacklist",
  },
  {
    aliases: ["company whitelist", "preferred companies"],
    applyMode: "needs_review",
    key: "companyWhitelist",
    operation: "replace_search_preferences_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.searchPreferences.companyWhitelist,
    reviewDomain: "search_preferences",
    title: "company whitelist",
  },
];
