import type { FieldDescriptor } from "./profile-copilot-field-updates-shared";
import {
  parseNullableList,
  parseNullableText,
} from "./profile-copilot-field-updates-shared";

export const contentFieldDescriptors: ReadonlyArray<FieldDescriptor<unknown>> = [
  {
    aliases: ["short value proposition", "value proposition"],
    applyMode: "applied",
    key: "shortValueProposition",
    operation: "replace_professional_summary_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.professionalSummary.shortValueProposition,
    reviewDomain: "professional_summary",
    title: "short value proposition",
  },
  {
    aliases: ["full summary", "professional summary"],
    applyMode: "applied",
    key: "fullSummary",
    operation: "replace_professional_summary_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.professionalSummary.fullSummary,
    reviewDomain: "professional_summary",
    title: "full summary",
  },
  {
    aliases: ["career themes"],
    applyMode: "applied",
    key: "careerThemes",
    operation: "replace_professional_summary_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.professionalSummary.careerThemes,
    reviewDomain: "professional_summary",
    title: "career themes",
  },
  {
    aliases: ["leadership summary"],
    applyMode: "applied",
    key: "leadershipSummary",
    operation: "replace_professional_summary_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.professionalSummary.leadershipSummary,
    reviewDomain: "professional_summary",
    title: "leadership summary",
  },
  {
    aliases: ["domain focus summary", "domain focus"],
    applyMode: "applied",
    key: "domainFocusSummary",
    operation: "replace_professional_summary_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.professionalSummary.domainFocusSummary,
    reviewDomain: "professional_summary",
    title: "domain focus summary",
  },
  {
    aliases: ["strengths"],
    applyMode: "applied",
    key: "strengths",
    operation: "replace_professional_summary_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.professionalSummary.strengths,
    reviewDomain: "professional_summary",
    title: "strengths",
  },
  {
    aliases: ["professional story", "story", "narrative"],
    applyMode: "applied",
    key: "professionalStory",
    operation: "replace_narrative_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.narrative.professionalStory,
    reviewDomain: "narrative",
    title: "professional story",
  },
  {
    aliases: ["next chapter summary", "next chapter"],
    applyMode: "applied",
    key: "nextChapterSummary",
    operation: "replace_narrative_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.narrative.nextChapterSummary,
    reviewDomain: "narrative",
    title: "next chapter summary",
  },
  {
    aliases: ["career transition summary", "career transition explanation"],
    applyMode: "applied",
    key: "careerTransitionSummary",
    operation: "replace_narrative_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.narrative.careerTransitionSummary,
    reviewDomain: "narrative",
    title: "career transition summary",
  },
  {
    aliases: ["differentiators"],
    applyMode: "applied",
    key: "differentiators",
    operation: "replace_narrative_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.narrative.differentiators,
    reviewDomain: "narrative",
    title: "differentiators",
  },
  {
    aliases: ["motivation themes", "motivations"],
    applyMode: "applied",
    key: "motivationThemes",
    operation: "replace_narrative_fields",
    parseValue: parseNullableList,
    readCurrentValue: (input) => input.profile.narrative.motivationThemes,
    reviewDomain: "narrative",
    title: "motivation themes",
  },
  {
    aliases: ["work authorization answer", "work authorization"],
    applyMode: "applied",
    key: "workAuthorization",
    operation: "replace_answer_bank_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.answerBank.workAuthorization,
    reviewDomain: "answer_bank",
    title: "work authorization answer",
  },
  {
    aliases: ["visa sponsorship answer"],
    applyMode: "applied",
    key: "visaSponsorship",
    operation: "replace_answer_bank_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.answerBank.visaSponsorship,
    reviewDomain: "answer_bank",
    title: "visa sponsorship answer",
  },
  {
    aliases: ["relocation answer"],
    applyMode: "applied",
    key: "relocation",
    operation: "replace_answer_bank_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.answerBank.relocation,
    reviewDomain: "answer_bank",
    title: "relocation answer",
  },
  {
    aliases: ["travel answer"],
    applyMode: "applied",
    key: "travel",
    operation: "replace_answer_bank_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.answerBank.travel,
    reviewDomain: "answer_bank",
    title: "travel answer",
  },
  {
    aliases: ["notice period answer"],
    applyMode: "applied",
    key: "noticePeriod",
    operation: "replace_answer_bank_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.answerBank.noticePeriod,
    reviewDomain: "answer_bank",
    title: "notice period answer",
  },
  {
    aliases: ["availability answer", "availability"],
    applyMode: "applied",
    key: "availability",
    operation: "replace_answer_bank_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.answerBank.availability,
    reviewDomain: "answer_bank",
    title: "availability answer",
  },
  {
    aliases: ["salary expectations answer", "salary expectations"],
    applyMode: "applied",
    key: "salaryExpectations",
    operation: "replace_answer_bank_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.answerBank.salaryExpectations,
    reviewDomain: "answer_bank",
    title: "salary expectations answer",
  },
  {
    aliases: ["short self introduction", "self introduction", "intro answer"],
    applyMode: "applied",
    key: "selfIntroduction",
    operation: "replace_answer_bank_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.answerBank.selfIntroduction,
    reviewDomain: "answer_bank",
    title: "short self-introduction",
  },
  {
    aliases: ["career transition answer"],
    applyMode: "applied",
    key: "careerTransition",
    operation: "replace_answer_bank_fields",
    parseValue: parseNullableText,
    readCurrentValue: (input) => input.profile.answerBank.careerTransition,
    reviewDomain: "answer_bank",
    title: "career transition answer",
  },
];
